SELECT *  FROM MC_CLI_FISICA CROSS JOIN MC_CLIENTE;



SELECT PF.DT_NASCIMENTO,
PF.FL_SEXO_BIOLOGICO,
NR_CLIENTE,
C.NM_CLIENTE,
C.DS_EMAIL
FROM MC_CLI_FISICA PF INNER JOIN MC_CLIENTE C 
USING(NR_CLIENTE) ORDER BY NR_CLIENTE;



SELECT 
MC_PRODUTO.CD_PRODUTO, 
MC_PRODUTO.DS_PRODUTO, 
MC_PRODUTO.VL_UNITARIO,
MC_PRODUTO.TP_EMBALAGEM,
MC_PRODUTO.VL_PERC_LUCRO,
MC_CATEGORIA_PROD.CD_CATEGORIA, 
MC_CATEGORIA_PROD.DS_CATEGORIA
FROM MC_PRODUTO INNER JOIN MC_CATEGORIA_PROD 
ON MC_PRODUTO.CD_PRODUTO = MC_CATEGORIA_PROD.CD_CATEGORIA 
ORDER BY MC_PRODUTO.DS_PRODUTO, MC_CATEGORIA_PROD.DS_CATEGORIA ASC; 



SELECT 
PF.DT_NASCIMENTO,
PF.FL_SEXO_BIOLOGICO,
C.NM_CLIENTE,
C.DS_EMAIL,
E.NR_END,
E.ST_END
FROM 
MC_CLI_FISICA PF 
INNER JOIN MC_CLIENTE C ON (PF.NR_CLIENTE = C.NR_CLIENTE) 
INNER JOIN MC_END_CLI E ON (E.NR_CLIENTE = C.NR_CLIENTE)
ORDER BY PF.NR_CLIENTE ASC;



SELECT 
C.NM_CLIENTE,
C.DS_EMAIL,
NR_CLIENTE,
PF.DT_NASCIMENTO,
PF.NR_CPF,
E.NR_END,
E.DT_INICIO
FROM 
MC_CLIENTE C 
INNER JOIN MC_CLI_FISICA PF USING(NR_CLIENTE)
INNER JOIN MC_END_CLI E USING(NR_CLIENTE)
ORDER BY NR_CLIENTE ASC;



-- Exibir: código e nome do cliente, e-mail, telefone, login, data de nascimento no formato dia-mes-ano (com 4 digitos), 
-- Dia da semana da data de nascimento, anos de vida, sexo biológico e CPF.
SELECT 
NR_CLIENTE,
C.NM_CLIENTE,
C.DS_EMAIL,
C.NR_TELEFONE,
C.NM_LOGIN,
PF.FL_SEXO_BIOLOGICO,
PF.NR_CPF,
PF.DT_NASCIMENTO,
TO_CHAR(DT_NASCIMENTO, 'DAY') "DIA DA SEMANA",
TO_CHAR(SYSDATE, 'YYYY') - TO_CHAR(DT_NASCIMENTO, 'YYYY') "ANOS DE VIDA" 
FROM MC_CLI_FISICA PF INNER JOIN MC_CLIENTE C
USING(NR_CLIENTE) ORDER BY NR_CLIENTE;













