CREATE SEQUENCE SQ_CATIGURIA
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCACHE
NOCYCLE
;



CREATE TABLE CATIGURIA_TESTE(
ID_CATIGURIA NUMBER DEFAULT SQ_CATIGURIA.NEXTVAL PRIMARY KEY NOT NULL,
NOME_CATIGURIA VARCHAR(150),
SIGLA_CATIGURIA CHAR(4)
);



CREATE TABLE TB_PUTERIN(
ID_PUTERIN VARCHAR(150) GENERATED ALWAYS AS IDENTITY NOT NULL,
NOME_PUTERIN VARCHAR(150),
SIGLA_PUTERIN CHAR(4)
);


DROP TABLE CATIGURIA_TESTE;
DROP TABLE TESTE_03;

DROP SEQUENCE SQ_CATIGURIA ;
DROP SEQUENCE SQ_TESTE_SEQ ;